### ISSUE TITLE
Ground Check et contact entre joueurs

### ISSUE THREAD

**Issue by Fayveline** [Falquano/Proto-Coop-Plateformer#4]
Lorsque 2 joueurs sont en contact ils créent des particules d'impact en boucle.

**Comment by SebPautot** [comment]
Fixed with commit d2661210f60cc5753ddd2899cf515867dd573405


Multiple object collisions happening at the same frame with OnCollisionStay returning different IsGrounded results caused issues.
Updating each frame with all collision points fixed the issue.
