### ISSUE TITLE
Coyote Time

### ISSUE THREAD

**Issue by Fayveline** [Falquano/Proto-Coop-Plateformer#5]
Il ne fonctionne pas. Il est actuellement réglé à 10 secondes et rien ne se produit.

Il faut aussi qu'il soit intégré pour le wall jump (là c'est un peu corsé de faire un wall jump vers le côté).

**Comment by SebPautot** [comment]
Fixed in commit 3c81be2f3eb41b70db2796ddb22d5d2527c15e01

An else was setting coyote to -1 but the condition above wasn't correctly triggered because the "jumped" variable was set to false when grounded and not when landing only.
