### ISSUE TITLE
Plus de particules de marche ?

### ISSUE THREAD

**Issue by Fayveline** [Falquano/Proto-Coop-Plateformer#6]
Il n'y a plus de particule de déplacement.

**Comment by Fayveline** [comment]
Ah ben il n'y a plus de trail lorsqu'on saute non plus !

**Comment by SebPautot** [comment]
Trail fixed with 4bfd33d980ea1aa58fe11726634f8c9770add015

**Comment by SebPautot** [comment]
Particules fixed with e56e34c637bb6ae064cfe940e6fef5a009591ffa
